apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-1
  labels:
    app: web-server-1
  namespace: default
spec:
  selector:
    matchLabels:
      app: web-server-1
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: web-server-1
    spec:
      containers:
      - name: web-server-1
        image: web-server-1:1.0
        ports:
        - containerPort: 8080        
