apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: web-server-1
  labels:
    app: web-server-1
spec:
  type: ClusterIP
  selector:
    app: web-server-1
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080
